[package]
name = "zffmount"
version = "2.0.0-rc.2"
edition = "2024"
rust-version = "1.85.0"
license = "MIT OR Apache-2.0"
description = "A command line utility to mount a zff container using FUSE."
homepage = "https://zff.dev"
repository = "https://github.com/zff-team/zffmount"
keywords = ["forensics", "security", "file-format", "file"]
categories = ["command-line-utilities"]
publish = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.6.1", features = [ "derive" ] }
zff = { path="../zff-rs", features = [ "log" ] }
walkdir = "2.3.2"
time = { version = "0.3.47", features = [ "formatting" ] }
#logging
log = "0.4"
env_logger = "0.11.10"
#serialize
serde = { version = "1.0.228", features = ["derive"] }
hex = "0.4.3"
toml = "1.1.2"
dialoguer = "0.12"
redb = "4.1.0"

[target.'cfg(target_family = "unix")'.dependencies]
nix = { version = "0.31.3", features = [ "user" ] }
signal-hook = "0.4.4"

[target.'cfg(target_os = "linux")'.dependencies]
fuser = { version = "0.17", features = ["abi-7-40"]}

[target.'cfg(target_os = "macos")'.dependencies]
fuser = { version = "0.17", features = ["libfuse"]}

[target.'cfg(target_os = "windows")'.dependencies]
winfsp = "0.12"
windows-sys = { version = "0.59", features = ["Win32_Storage_FileSystem", "Win32_Security", "Win32_System_Memory", "Win32_Foundation"] }
ctrlc = "3.5.2"

[target.'cfg(target_os = "windows")'.build-dependencies]
winfsp = "0.12"

[profile.release]
lto = true				# enables link time optimization
panic = 'unwind'		# unwinds the stack if panic
debug = false			# I won't see any debug options in release mode.
opt-level = 2  			# optimized for performance.
codegen-units = 1		# Set to 1 to allow for maximum size reduction optimizations - at the expense of the compile time.
