# base information
name: zffmount
adopt-info: zffmount
summary: Tool to fuse-mount zff files.
description: |
  zffmount is a tool to mount zff files with FUSE.
issues: https://github.com/zff-team/zffmount/issues
source-code: https://github.com/zff-team/zffmount
website: https://zff.dev
# snapcraft information
base: core22

grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
  - build-on: arm64

# snapcraft
parts:
  # install rust manually
  rust-deps:
    plugin: nil
    build-packages:
      - curl
    override-pull: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

  zffmount:
    after: [ rust-deps ]
    build-packages: [ gcc, fuse3, libfuse3-dev, pkg-config, libacl1-dev ]
    stage-packages: [ fuse3 ]
    plugin: rust
    source: .
    override-pull: |
      snapcraftctl pull
      VERSION="$(git describe --tags --abbrev=0)"
      [ -n "$(echo $VERSION)" ] && GRADE=stable
      snapcraftctl set-version "$VERSION"
      snapcraftctl set-grade "$GRADE"
    override-stage: |
      snapcraftctl stage
      chmod u+s bin/fusermount3
      chmod u+s sbin/mount.fuse3
plugs:
  mntctl:
    interface: mount-control
    namespace: host
    mount:
      - what: /**
        where: /**
        type: [ fuse ]
        options: [ rw, async, ro, nosuid, nodev, relatime ]
apps:
  zffmount:
    command: bin/zffmount
    plugs: [mntctl, fuse-support]